### ISSUE TITLE
bundler/setup (LoadError)

### ISSUE THREAD

**Issue by dannymichel** [jlund/spotify-export#12]
```
➜  spotify-export git:(master) ✗ ./bin/spotify-export.rb your-filename.txt
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./bin/spotify-export.rb:3:in `<main>'
```

**Comment by CorbanR** [comment]
Ensure you have bundler installed at the latest version  `gem install bundler`

**Comment by jlund** [comment]
Yeah, an out-of-date version of Bundler would throw that error. Let me know if updating Bundler doesn't fix the issue.
