### ISSUE TITLE
cannot load such file -- bundler/setup (LoadError)

### ISSUE THREAD

**Issue by ketansweta** [jlund/spotify-export#18]
Downloaded the latest bundle - running my command I get the below error - 
what am I missing ? 

bash-3.2$ ./spotify-export.rb test2.txt 
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./spotify-export.rb:3:in `<main>'
bash-3.2$

**Comment by tmeedend** [comment]
I am also experiencing this problem

**Comment by BachirC** [comment]
Are you in the `bin` folder when doing that ? If you are in the root, it's `./bin/spotify-export.rb`.

**Comment by kmorlack** [comment]
I am still hitting this error, anyone solve it?
