### ISSUE TITLE
`initialize': That file does not exist (SpotifyPlaylist::MissingFileError)

### ISSUE THREAD

**Issue by jpswade** [jlund/spotify-export#20]
```
$ ./bin/spotify-export.rb spotify.txt
/usr/local/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:206: warning: constant ::Fixnum is deprecated
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/usr/local/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:230: warning: constant ::Fixnum is deprecated
/usr/local/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:230: warning: constant ::Fixnum is deprecated
.../spotify-export/lib/spotify-playlist.rb:10:in `initialize': That file does not exist (SpotifyPlaylist::MissingFileError)
	from ./bin/spotify-export.rb:16:in `new'
	from ./bin/spotify-export.rb:16:in `<main>'
```

**Comment by BachirC** [comment]
Did you make sure the file `spotify.txt` exists ? If it does, try to find out what file it is trying to open.
