### ISSUE TITLE
`format_artists': undefined method `each' 

### ISSUE THREAD

**Issue by afrankel-sfdo** [jlund/spotify-export#22]
- ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
- macOS High Sierra 10.13.2 (17C88)

Ran: `./bin/spotify-export.rb ~/Desktop/jazz.txt`

```
/usr/local/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:230: warning: constant ::Fixnum is deprecated
Traceback (most recent call last):                                                                                             |
	7: from ./bin/spotify-export.rb:20:in `<main>'
	6: from ./bin/spotify-export.rb:20:in `each_with_index'
	5: from ./bin/spotify-export.rb:20:in `each'
	4: from ./bin/spotify-export.rb:23:in `block in <main>'
	3: from /Users/af/Code/spotify-export/lib/spotify-track.rb:22:in `name'
	2: from /Users/af/Code/spotify-export/lib/spotify-track.rb:32:in `attributes'
	1: from /Users/af/Code/spotify-export/lib/spotify-track.rb:82:in `get_track_attributes'
/Users/af/Code/spotify-export/lib/spotify-track.rb:49:in `format_artists': undefined method `each' for nil:NilClass (NoMethodError)
```

**Comment by BachirC** [comment]
Hey, it is addressed in this issue #17
